const countries = [
  { id: 1, name: "Nigeria", code: "NG", continent: "Africa" },
  { id: 2, name: "South Africa", code: "ZA", continent: "Africa" },
  { id: 3, name: "Egypt", code: "EG", continent: "Africa" },
  { id: 4, name: "Kenya", code: "KE", continent: "Africa" },
  { id: 5, name: "Ethiopia", code: "ET", continent: "Africa" },
  { id: 6, name: "Morocco", code: "MA", continent: "Africa" },
  { id: 7, name: "Ghana", code: "GH", continent: "Africa" },
  { id: 8, name: "Algeria", code: "DZ", continent: "Africa" },
  { id: 9, name: "Uganda", code: "UG", continent: "Africa" },
  { id: 10, name: "Tanzania", code: "TZ", continent: "Africa" },
  { id: 11, name: "Germany", code: "DE", continent: "Europe" },
  { id: 12, name: "France", code: "FR", continent: "Europe" },
  { id: 13, name: "United Kingdom", code: "GB", continent: "Europe" },
  { id: 14, name: "Italy", code: "IT", continent: "Europe" },
  { id: 15, name: "Spain", code: "ES", continent: "Europe" },
  { id: 16, name: "Poland", code: "PL", continent: "Europe" },
  { id: 17, name: "Netherlands", code: "NL", continent: "Europe" },
  { id: 18, name: "Belgium", code: "BE", continent: "Europe" },
  { id: 19, name: "Greece", code: "GR", continent: "Europe" },
  { id: 20, name: "Portugal", code: "PT", continent: "Europe" },
  { id: 21, name: "China", code: "CN", continent: "Asia" },
  { id: 22, name: "India", code: "IN", continent: "Asia" },
  { id: 23, name: "Japan", code: "JP", continent: "Asia" },
  { id: 24, name: "South Korea", code: "KR", continent: "Asia" },
  { id: 25, name: "Indonesia", code: "ID", continent: "Asia" },
  { id: 26, name: "Vietnam", code: "VN", continent: "Asia" },
  { id: 27, name: "Philippines", code: "PH", continent: "Asia" },
  { id: 28, name: "Thailand", code: "TH", continent: "Asia" },
  { id: 29, name: "Pakistan", code: "PK", continent: "Asia" },
  { id: 30, name: "Bangladesh", code: "BD", continent: "Asia" },
];

export default countries;
