const leads = [
  {
    Name: "Sarah Johnson",
    Date: "2/12/2024",
    Customer: "Teslack Organization",
    ClientType: "Company",
    Stage: "Pending",
    MobileNumber: "0824567890",
    Email: "sarahjohnson@example.com",
    Country: "South Africa",
  },
  {
    Customer: "John Doe",
    Date: "3/12/2024",
    Name: "John Doe",
    ClientType: "Individual",
    Stage: "Pending",
    MobileNumber: "0821234567",
    Email: "johndoe@example.com",
    Country: "South Africa",
  },
  {
    Customer: "Jane Smith",
    Date: "4/12/2024",
    Name: "Jane Smith",
    ClientType: "Trust",
    Stage: "Pending",
    MobileNumber: "0822345678",
    Email: "janesmith@example.com",
    Country: "South Africa",
  },
  {
    Customer: "ABC Corporation",
    Date: "5/12/2024",
    Name: "Michael Brown",
    ClientType: "Company",
    Stage: "Pending",
    MobileNumber: "0823456789",
    Email: "michaelbrown@example.com",
    Country: "United States",
  },
  {
    Customer: "David Wilson",
    Date: "6/12/2024",
    Name: "David Wilson",
    ClientType: "Individual",
    Stage: "Pending",
    MobileNumber: "0825678901",
    Email: "davidwilson@example.com",
    Country: "United Kingdom",
  },
  {
    Customer: "Crios Trust",
    Date: "7/12/2024",
    Name: "Emily Davis",
    ClientType: "Trust",
    Stage: "Pending",
    MobileNumber: "0826789012",
    Email: "emilydavis@example.com",
    Country: "South Africa",
  },
  {
    Customer: "CrioSoft",
    Date: "8/12/2024",
    Name: "Daniel Martinez",
    ClientType: "Company",
    Stage: "Pending",
    MobileNumber: "0827890123",
    Email: "danielmartinez@example.com",
    Country: "Canada",
  },
  {
    Customer: "Olivia Garcia Partners",
    Date: "9/12/2024",
    Name: "Olivia Garcia",
    ClientType: "Partnership",
    Stage: "Pending",
    MobileNumber: "0828901234",
    Email: "oliviagarcia@example.com",
    Country: "South Africa",
  },
  {
    Customer: "Liam White",
    Date: "10/12/2024",
    Name: "Liam White",
    ClientType: "Individual",
    Stage: "Pending",
    MobileNumber: "0829012345",
    Email: "liamwhite@example.com",
    Country: "Australia",
  },
  {
    Customer: "Lia Trust",
    Date: "12/12/2024",
    Name: "Sophia Lewis",
    ClientType: "Trust",
    Stage: "Pending",
    MobileNumber: "0830123456",
    Email: "sophialewis@example.com",
    Country: "South Africa",
  },
  // {
  //   Name: "William Clark",
  //   ClientType: "Company",
  //   Stage: "Pending",
  //   MobileNumber: "0831234567",
  //   Email: "williamclark@example.com",
  //   Country: "Germany",
  // },
  // {
  //   Name: "Mia Young",
  //   ClientType: "Partnership",
  //   Stage: "Pending",
  //   MobileNumber: "0832345678",
  //   Email: "miayoung@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "James Walker",
  //   ClientType: "Individual",
  //   Stage: "Pending",
  //   MobileNumber: "0833456789",
  //   Email: "jameswalker@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Isabella King",
  //   ClientType: "Trust",
  //   Stage: "Pending",
  //   MobileNumber: "0834567890",
  //   Email: "isabellaking@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Benjamin Wright",
  //   ClientType: "Company",
  //   Stage: "Pending",
  //   MobileNumber: "0835678901",
  //   Email: "benjaminwright@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Charlotte Harris",
  //   ClientType: "Partnership",
  //   Stage: "Pending",
  //   MobileNumber: "0836789012",
  //   Email: "charlotteharris@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Lucas Thomas",
  //   ClientType: "Individual",
  //   Stage: "Pending",
  //   MobileNumber: "0837890123",
  //   Email: "lucasthomas@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Amelia Scott",
  //   ClientType: "Trust",
  //   Stage: "Pending",
  //   MobileNumber: "0838901234",
  //   Email: "ameliascott@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Ethan Adams",
  //   ClientType: "Company",
  //   Stage: "Pending",
  //   MobileNumber: "0839012345",
  //   Email: "ethanadams@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Ava Nelson",
  //   ClientType: "Partnership",
  //   Stage: "Pending",
  //   MobileNumber: "0840123456",
  //   Email: "avanelson@example.com",
  //   Country: "New Zealand",
  // },
  // {
  //   Name: "Oscar Reid",
  //   ClientType: "Individual",
  //   Stage: "Pending",
  //   MobileNumber: "0841234567",
  //   Email: "oscarreid@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Sophia James",
  //   ClientType: "Trust",
  //   Stage: "Pending",
  //   MobileNumber: "0842345678",
  //   Email: "sophiajames@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Eleanor Clark",
  //   ClientType: "Company",
  //   Stage: "Pending",
  //   MobileNumber: "0843456789",
  //   Email: "eleanorclark@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Jacob Foster",
  //   ClientType: "Partnership",
  //   Stage: "Pending",
  //   MobileNumber: "0844567890",
  //   Email: "jacobfoster@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Henry Mitchell",
  //   ClientType: "Individual",
  //   Stage: "Pending",
  //   MobileNumber: "0845678901",
  //   Email: "henrymitchell@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Natalie Edwards",
  //   ClientType: "Trust",
  //   Stage: "Pending",
  //   MobileNumber: "0846789012",
  //   Email: "natalieedwards@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Mason Turner",
  //   ClientType: "Company",
  //   Stage: "Pending",
  //   MobileNumber: "0847890123",
  //   Email: "masonturner@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Grace Evans",
  //   ClientType: "Partnership",
  //   Stage: "Pending",
  //   MobileNumber: "0848901234",
  //   Email: "graceevans@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Lucas Hill",
  //   ClientType: "Individual",
  //   Stage: "Pending",
  //   MobileNumber: "0849012345",
  //   Email: "lucashill@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Chloe Roberts",
  //   ClientType: "Trust",
  //   Stage: "Pending",
  //   MobileNumber: "0850123456",
  //   Email: "chloeroberts@example.com",
  //   Country: "South Africa",
  // },

  // // Continue adding more leads with varied data to reach 30 records with "Pending" status
  // {
  //   Name: "Sophia Taylor",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567001",
  //   Email: "sophiataylor@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Liam Johnson",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567002",
  //   Email: "liamjohnson@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Olivia Brown",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567003",
  //   Email: "oliviabrown@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Noah Jones",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567004",
  //   Email: "noahjones@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Emma Garcia",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567005",
  //   Email: "emmagarcia@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Lucas Martinez",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567006",
  //   Email: "lucasmartinez@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Mia Rodriguez",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567007",
  //   Email: "miarodriguez@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "James Wilson",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567008",
  //   Email: "jameswilson@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Isabella Lopez",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567009",
  //   Email: "isabellalopez@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Elijah White",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567010",
  //   Email: "elijahwhite@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Ava Hall",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567011",
  //   Email: "avahall@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Ethan Young",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567012",
  //   Email: "ethanyoung@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Charlotte King",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567013",
  //   Email: "charlotteking@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Benjamin Wright",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567014",
  //   Email: "benjaminwright@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Amelia Scott",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567015",
  //   Email: "ameliascott@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Henry Harris",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567016",
  //   Email: "henryharris@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Abigail Green",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567017",
  //   Email: "abigailgreen@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Samuel Adams",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567018",
  //   Email: "samueladams@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Ella Nelson",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567019",
  //   Email: "ellanelson@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Daniel Carter",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567020",
  //   Email: "danielcarter@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Grace Mitchell",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567021",
  //   Email: "gracemitchell@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Alexander Perez",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567022",
  //   Email: "alexanderperez@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Sofia Roberts",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567023",
  //   Email: "sofiaroberts@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Jackson Collins",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567024",
  //   Email: "jacksoncollins@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Avery Stewart",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567025",
  //   Email: "averystewart@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Sebastian Morris",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567026",
  //   Email: "sebastianmorris@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Scarlett Cooper",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567027",
  //   Email: "scarlettcooper@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Matthew Bell",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567028",
  //   Email: "matthewbell@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Emily Brooks",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567029",
  //   Email: "emilybrooks@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Isaac Torres",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567030",
  //   Email: "isaactorres@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Hannah Sanchez",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567031",
  //   Email: "hannahsanchez@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Luke Ramirez",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567032",
  //   Email: "lukeramirez@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Zoe Reed",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567033",
  //   Email: "zoereed@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Logan Rivera",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567034",
  //   Email: "loganrivera@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Chloe Powell",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567035",
  //   Email: "chloepowell@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Levi Foster",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567036",
  //   Email: "levifoster@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Lily Ross",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567037",
  //   Email: "lilyross@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Gabriel Wood",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567038",
  //   Email: "gabrielwood@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Zara Lee",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567039",
  //   Email: "zaralee@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "David Ward",
  //   ClientType: "Partnership",
  //   Stage: "Approved",
  //   MobileNumber: "0824567040",
  //   Email: "davidward@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Penelope Hughes",
  //   ClientType: "Individual",
  //   Stage: "Approved",
  //   MobileNumber: "0824567041",
  //   Email: "penelopehughes@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Aaron Patterson",
  //   ClientType: "Company",
  //   Stage: "Approved",
  //   MobileNumber: "0824567042",
  //   Email: "aaronpatterson@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Victoria Butler",
  //   ClientType: "Trust",
  //   Stage: "Approved",
  //   MobileNumber: "0824567043",
  //   Email: "victoriabutler@example.com",
  //   Country: "South Africa",
  // },
  // // Repeat until you have 100 records with "Approved" status
  // {
  //   Name: "Caleb Brooks",
  //   ClientType: "Individual",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0855678901",
  //   Email: "calebbrooks@example.com",
  //   Country: "New Zealand",
  // },
  // {
  //   Name: "Mila Powell",
  //   ClientType: "Trust",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0856789012",
  //   Email: "milapowell@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Sebastian Price",
  //   ClientType: "Company",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0857890123",
  //   Email: "sebastianprice@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Aria Bell",
  //   ClientType: "Partnership",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0858901234",
  //   Email: "ariabell@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Harper Ward",
  //   ClientType: "Individual",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0859012345",
  //   Email: "harperward@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Jackson Perez",
  //   ClientType: "Trust",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0860123456",
  //   Email: "jacksonperez@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Ella Gray",
  //   ClientType: "Company",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0861234567",
  //   Email: "ellagray@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Liam Murphy",
  //   ClientType: "Partnership",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0862345678",
  //   Email: "liammurphy@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Charlotte Barnes",
  //   ClientType: "Individual",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0863456789",
  //   Email: "charlottebarnes@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Amelia Shaw",
  //   ClientType: "Trust",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0864567890",
  //   Email: "ameliashaw@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "Henry Patterson",
  //   ClientType: "Company",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0865678901",
  //   Email: "henrypatterson@example.com",
  //   Country: "New Zealand",
  // },
  // {
  //   Name: "Lucas Wallace",
  //   ClientType: "Partnership",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0866789012",
  //   Email: "lucaswallace@example.com",
  //   Country: "Australia",
  // },
  // {
  //   Name: "Isla Mitchell",
  //   ClientType: "Individual",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0867890123",
  //   Email: "islamitchell@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Oscar Knight",
  //   ClientType: "Trust",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0868901234",
  //   Email: "oscarKnight@example.com",
  //   Country: "United States",
  // },
  // {
  //   Name: "Grace Cooper",
  //   ClientType: "Company",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0869012345",
  //   Email: "gracecooper@example.com",
  //   Country: "United Kingdom",
  // },
  // {
  //   Name: "Emily Turner",
  //   ClientType: "Partnership",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0870123456",
  //   Email: "emilyturner@example.com",
  //   Country: "Canada",
  // },
  // {
  //   Name: "James Simmons",
  //   ClientType: "Individual",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0871234567",
  //   Email: "jamessimmons@example.com",
  //   Country: "India",
  // },
  // {
  //   Name: "Olivia Brooks",
  //   ClientType: "Trust",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0872345678",
  //   Email: "oliviabrooks@example.com",
  //   Country: "South Africa",
  // },
  // {
  //   Name: "Aiden Diaz",
  //   ClientType: "Company",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0873456789",
  //   Email: "aidendiaz@example.com",
  //   Country: "New Zealand",
  // },
  // {
  //   Name: "Evelyn Hayes",
  //   ClientType: "Partnership",
  //   Stage: "With Compliance Team",
  //   MobileNumber: "0874567890",
  //   Email: "evelynhayes@example.com",
  //   Country: "Australia",
  // },
];

export default leads;
